### ISSUE TITLE
Form field validations

### ISSUE THREAD

**Issue by salvadorcastro** [c15k0/psfs#12]
There's an issue in the function **_isValid_** inside _**src/base/types/Form.php**_. It's only taken into account the last field in order to validate the form; also the token field is checked twice, one at the beginning of the function and another along with the rest of the fields, so that if the token field is valid, the whole form will be valid.

**Comment by c15k0** [comment]
#13

**Comment by c15k0** [comment]
Resolved in #13

**Comment by salvadorcastro** [comment]
There's a misspelling in the same file, line 341: "El campo %s es **oligatorio**"
